import Head from 'next/head';
import { Cursor, useTypewriter } from "react-simple-typewriter";
import MainTitle from "../components/MainTitle";

export default function Home() {
  const { text, count } = useTypewriter({
    words: ["fix.", "create.", "are NetUnion."],
    loop: 0,
  });

  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <MainTitle />
    <p className="slogan">We {text}<Cursor /></p>

    {/* <h2>我们是什么</h2> */}
    <p>我们是电子科技大学宿舍网络管理委员会（NetUnion，简称 NU）。我们是成立 25 年的学生组织，历经变迁，现隶属于信息中心，参与校内网络基础设施维护工作，为全校学生提供<a href="http://mirrors.uestc.cn">开源软件镜像站</a>等诸多服务。</p>
    {/* <h2>我们的条件</h2>
    <ul>
      <li>办公处所位置便利，电力与网络顺畅稳定</li>
      <li>内部藏书种类繁多，团建活动定期举办</li>
      <li>够用的服务器资源，助你实现天才想法</li>
      <li>零距离接触生产环境网络设备的有趣经验</li>
      <li>勤工助学有偿服务机会</li>
    </ul> */}
    {/* <h2>招新</h2>
    <p>我们面对<b>全体电子科技大学学生</b>招新。</p> */}
  </>;
};
